"""Offline model experiment registry with reproducibility and quality gates."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Literal
from uuid import uuid4

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field, model_validator


class ExperimentPlan(BaseModel):
    """Reproducible training contract consumed by a dedicated GPU worker."""

    method: Literal["lora", "qlora", "dpo", "grpo", "distributed"]
    base_model: str
    base_model_revision: str
    dataset_uri: str
    dataset_sha256: str = Field(pattern=r"^[a-f0-9]{64}$")
    container_image_digest: str
    random_seed: int
    parameters: dict[str, object] = Field(default_factory=dict)
    evaluation_thresholds: dict[str, float] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_method_parameters(self):
        """校验 validate_method_parameters 对应的受控业务步骤。


        Require method-specific reproducibility inputs before a GPU worker can be scheduled.
        """
        if self.method in {"lora", "qlora"} and "lora_rank" not in self.parameters:
            raise ValueError("LoRA/QLoRA plans require parameters.lora_rank")
        if (
            self.method in {"dpo", "grpo"}
            and "preference_dataset_uri" not in self.parameters
        ):
            raise ValueError("DPO/GRPO plans require a preference dataset")
        if self.method == "distributed" and "launcher" not in self.parameters:
            raise ValueError("distributed plans require parameters.launcher")
        return self


class EvaluationResult(BaseModel):
    """Metrics emitted by an offline evaluator, not generated by an LLM judge alone."""

    metrics: dict[str, float]
    benchmark_version: str
    evaluator_image_digest: str


class ModelCard(BaseModel):
    artifact_uri: str
    artifact_sha256: str = Field(pattern=r"^[a-f0-9]{64}$")
    quantization: str | None = None
    license: str
    intended_use: str
    limitations: list[str] = Field(default_factory=list)


class ExperimentRecord(BaseModel):
    experiment_id: str
    plan: ExperimentPlan
    status: Literal["PLANNED", "EVALUATED", "REJECTED", "APPROVED"] = "PLANNED"
    evaluation: EvaluationResult | None = None
    model_card: ModelCard | None = None
    created_at: datetime


records: dict[str, ExperimentRecord] = {}
app = FastAPI(title="Agent Platform Model Lab")


@app.post("/v1/experiments", response_model=ExperimentRecord)
def create_experiment(plan: ExperimentPlan) -> ExperimentRecord:
    """创建或构建 create_experiment 对应的受控业务步骤。


    Register an immutable plan before an external GPU job is started.
    """
    experiment_id = f"exp_{uuid4().hex}"
    record = ExperimentRecord(
        experiment_id=experiment_id, plan=plan, created_at=datetime.now(UTC)
    )
    records[experiment_id] = record
    return record


@app.post("/v1/experiments/{experiment_id}/evaluate", response_model=ExperimentRecord)
def record_evaluation(experiment_id: str, result: EvaluationResult) -> ExperimentRecord:
    """处理 record_evaluation 对应的当前组件内部业务步骤。


    Gate promotion using threshold comparisons that are deterministic and auditable.
    """
    record = records.get(experiment_id)
    if record is None:
        raise HTTPException(404, "experiment not found")
    failed = [
        name
        for name, threshold in record.plan.evaluation_thresholds.items()
        if result.metrics.get(name, float("-inf")) < threshold
    ]
    record.evaluation = result
    record.status = "REJECTED" if failed else "EVALUATED"
    records[experiment_id] = record
    return record


@app.post("/v1/experiments/{experiment_id}/model-card", response_model=ExperimentRecord)
def attach_model_card(experiment_id: str, card: ModelCard) -> ExperimentRecord:
    """处理 attach_model_card 对应的当前组件内部业务步骤。


    Approve an evaluated artifact only after its immutable identity and intended use are declared.
    """
    record = records.get(experiment_id)
    if record is None:
        raise HTTPException(404, "experiment not found")
    if record.status != "EVALUATED":
        raise HTTPException(
            409, "quality gate must pass before a model card is attached"
        )
    record.model_card = card
    record.status = "APPROVED"
    records[experiment_id] = record
    return record


@app.get("/v1/experiments/{experiment_id}", response_model=ExperimentRecord)
def get_experiment(experiment_id: str) -> ExperimentRecord:
    """读取或查询 get_experiment 对应的受控业务步骤。


    Return immutable experiment evidence for Control Plane release validation.
    """
    record = records.get(experiment_id)
    if record is None:
        raise HTTPException(404, "experiment not found")
    return record
